baseURL = "http://localhost:1313/"
title = "Old-school old-time hacker's lair"
theme = "jane"

defaultContentLanguage = "en"
[languages.en]
  languageCode = "en"

[author] # essential
  name = "sergei.nosov"

[sitemap] # essential
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[params]
  debug = false             # If true, load `eruda.min.js`. See https://github.com/liriliri/eruda
  since = "2018"            # Site creation time
  homeFullContent = false   # if false, show post summaries on home page. Otherwise, show full content.
  rssFullContent = true     # if false, RSS feed instead of the summary

  # site info (optional)
  logoTitle = "Lair"        # default: the title value
  keywords = []
  description = "Description"

  # paginate of archives, tags and categories
  archive-paginate = 3

  # paginate style, default use numbered pagination links
  # if true, use original "Previous" and "Next" links.
  # paginateOriginalStyle = true

  # The date format to use; for a list of valid formats, see https://gohugo.io/functions/format/
  dateFormatToUse = "2006-01-02"

  # show word count and read time ?
  moreMeta = false

  # show language chooser in menu
  showMenuLanguageChooser = true

  # Some global options, you can also close or open something in front matter for a single post, see more information from `archetypes/default.md`.
  toc = true
  photoswipe = true         # see https://github.com/dimsemenov/PhotoSwipe
  mathjax = false           # see https://www.mathjax.org/
  contentCopyright = '<a rel="license noopener" href="https://creativecommons.org/licenses/by-nc-nd/4.0/" target="_blank">CC BY-NC-ND 4.0</a>'

  [params.social]
    a-email = "mailto:your@email.com"
    b-stack-overflow = "http://localhost:1313"
    e-linkedin = "http://localhost:1313"
    f-google = "http://localhost:1313"
    g-github = "http://localhost:1313"
