---
title: "Open letter to Dr. Peterson"
date: 2018-09-18T15:45:44+03:00
weight: 50
---

Dear Dr. Peterson,

I, just as yourself, want people to know the truth about the world we're living
in. At this time, I aim for a very specific goal - to change a perspective of
one man, Jordan Peterson, on the subject that I consider to be important - the
events that took place in the USSR during 20th century and that are often
referred to as "Stalin's repressions". I won't try to change your views on
Marxism, socialism or communism. I will only provide you the objective picture
about the actual figures and scale of these events.

I went through a good share of videos with your lectures, but, again, to limit
the scope of this message, I will make my argument about the following video:

{{< youtube 8p2QfjaSIUo >}}

# more

* "Gulag Archipelago" reliability

If I see it right, in this video you reference the Gulag Archipelago as a
reasonable source of information, and the number of a 100 millions of victims of
repressions as sound.

I have a lot of friends and colleagues in the US and Europe and I kind of got
accustomed to the fact that Western people, in general, share a lot of
stereotypes about our country and its history. So, it doesn't surprise me when
people, like, James Hetfield [[https://www.youtube.com/watch?v=qmSgl4mwZ4Q][talk about "freaking commies"]] and re-translate every
single stereotype possible.

But when I see a man of science and reason, like yourself, bluntly repeating
Solzhenitsyn's lies about "a 100 million of corpses", it makes me think that the
Western propaganda has really done it's job well. And it makes me even more
concerned now, that there's, literally, no counterweight to this point anymore
after the USSR collapse

First, I will mention that Solzhenitsyn never had access to the statistics of
any sort to evaluate the number of victims. The number of 110 millions that
appeared in public thanks to him, was completely made up and had no reasonable
facts behind it. However, it was hugely popularized by 2 joint forces. One was
the Western world, who saw a threat in the USSR and was simply fighting a war
against it (sometimes Cold, sometimes an actual war). And the second force, as
surprising as it may sound, was the party nomenclature of late USSR. The very
core of the Soviet system was destroying their own state.

Not sure if I have to defend the last argument, since this is something plain
obvious to a person who lived through the Perestroika and knows the story from
the inside. If you take a look at Forbes list of richest people in the world,
you won't find a Russian Bill Gates there. All Russians in the list have made
their fortune during "privatization" - when the lands and mineral resources that
were once belonging to the state became their private property. By this I'm
implying that one of the reasons why USSR has collapsed is the desire of certain
elite groups to make a fortune on the dead body of a once great and rich state.

Anyway, my point is that there was no real counterpart to argue Solzhenitsyn at
that time. Pretty much everybody was interested to spread his very skewed point
of view. During the Perestroika this process got out of hand completely when it
became the actual politics. TV channels were competing in who provides the most
bizarre numbers and most bloody interpretations. The researches who were
spreading this kind of views got funding, they were printed in magazines and
invited to TV shows. The opposite point of view was marginalized due to nothing
more than ideology - the new government had to defend their right to rule by
showing how Soviet system was nothing more than a bloody nightmare.

Frankly, a lot of people, myself included, were under the same impression for
quite some time. The propaganda and lack of reasonable discussion was that
powerful. But as you can imagine, the real scientists did work on the
problem. It's just nobody was interested to listen to them.

* Victor Zemskov's interview

After this long prelude, we now, finally, come to the subject of interest. The
researcher who gave the first proper estimate to the number of victims of
"Stalin's repressions" was Victor Zemskov. This happened in the late 80s and 90s
as a result of his work in the scientific group that was brought together for
this sole purpose. It was the first time when researchers got access to the
(previously, top secret) documents of the executives of that time (NKVD, MVD,
etc.). And that allowed them to claim accuracy.

I will now present you a translation of one of Zemskov's interviews and present
3 links to his articles on the matter. Notice, that Zemskov himself shares quite
liberal views and uses pretty strict language, like "terrorist nature of the
regime", when making judgements of politics of those days. As you could,
probably, guess from the fact that I was motivated enough to write this letter,
I don't share his judgements and, actually, sympathize the state of the
USSR. But, unlike Solzhenitsyn, Zemskov was an honest researcher that went
through a great amount of work to find out the accurate numbers. And this is far
more important than the political views. So, here goes the interview.

- <samp>Are there any exact figures for the victims of Stalin's repressions?</samp>

#+BEGIN_QUOTE
The term "repression" can be interpreted in different ways. I confine myself to "political repressions", that is, those citizens who were charged with Article 58 of the Criminal Code (counter-revolutionary activity and other grave crimes against State) and who were sentenced to death or other measures of punishment. From 1921 to 1953 there were about 4 millions of such people. Of these, about 800,000 were sentenced to death. In addition, we assume that about 600,000 died in prison, so the total number of victims reaches 1.4 million.
#+END_QUOTE

- <samp>Are these 4 millions of whom 1.4 were killed, "kulaks", "deported nations", etc.?</samp>

#+BEGIN_QUOTE
"Kulaks" are divided into 3 categories. One of them includes arrested and convicted as political criminals. Yes, they are taken into account in our statistics. Another group consists of those deported to the north, and a third group - those who were simply expelled from the village and started working at the factories. The last two groups - the most numerous - were not taken into account in our research, so among these 4 millions there's just a small amount of "kulaks".
#+END_QUOTE

- <samp>Why they were not included? Are expulsion to the north and deportation not considered repression?</samp>

#+BEGIN_QUOTE
Yes, but they were not convicted. They were just deported with property confiscation. There's a place for a debate...
#+END_QUOTE

- <samp>That is, if there is no official verdict, then there's no repression?</samp>

#+BEGIN_QUOTE
This is the only way to distinguish politically repressed and those who have suffered in general. We believe that since 1918, when the expropriation of landowners, capitalists and clergy began, only those who were arrested by the Cheka should be considered repressed. It excludes people who lost all their property, but were not arrested. We would approach "kulaks" the same way: those who are arrested are considered to be repressed, while the deported simply fell victim to social and economic transformation - cruel and based on leveling. This can be applied to most of the population of the USSR, because everyone suffered to one degree or another: hunger, poor living conditions, etc.
#+END_QUOTE

- <samp>That's true, but you should also consder repressed other victims of terror, where mortality was often very high. For example, the convincing studies show that 1.1-1.2 million families of "kulaks" were destroyed in the process of collectivization, and how many of these 5.5-6 million died?</samp>

#+BEGIN_QUOTE
The digit has not yet been set. The bibliography contains absurd figures - from 6 to 10 million dead; among them from 3 to 7 million in Ukraine. However, thanks to demographic statistics, we know that in 1932, 780,000 were born in Ukraine, and 668,000 died, while in 1933, 359,000 were born, and 1.3 million died. These figures include natural mortality, but it is clear that the main cause of death in those years was hunger.
#+END_QUOTE

- <samp>Ukrainian nationalists consider this a national genocide against the Ukrainians; do you agree with this?</samp>

#+BEGIN_QUOTE
No, because other regions were in the same situation: the North Caucasus, the Volga region and Kazakhstan, where hunger also struck hard. Confiscating part of the harvest was necessary to fulfill the plan, but because of the drought, the entire crop was confiscated. The state committed a crime against all peasants, regardless of their nationality.
#+END_QUOTE

- <samp>14 nationalities of the USSR were deported in their full, and 48 - partially. Only among the Caucasian ethnic groups, 650,000 people were deported: it was carried out during three military operations, in which 100,000 of military personnel were involved, not counting 19,000 NKVD officers. What do you say about the mortality in this period?</samp>

#+BEGIN_QUOTE
In the course of the deportation operation itself, it wasn't very large. For example, if we talk about the Crimean Tatars, every train have lost 2-3 persons, mostly old people. A total of 191 people died. However, after arriving to Uzbekistan, tens of thousands of people died there. During the first year, the mortality rate was several times higher than the birth rate. If we talk about Chechens, the exact figures are unknown, but the story is the same - a few have died along the way, but a lot died on the new place.
#+END_QUOTE

- <samp>Why did you choose a time period of 1921-1953? Was there no more repressions after 1953?</samp>

#+BEGIN_QUOTE
In the period from 1937 to 1953, during the repression, a lot of people died. During the most cruel period - 1937-38 - more than 1.3 million people were convicted, and almost 700,000 were shot dead. In 1951, nearly 55,000 people were convicted, in 1952 - 29,000... Let's turn to 1958, when Stalin was no longer there: the number of convicts was lower than in 2000; 69 of them were sentenced to death. That is, the scale of repression decreased by 20 times compared with the beginning of 50-ies, and by hundreds of times compared to the 30-ies. Since Khrushchev, the figures of repressed already were insignificant.
#+END_QUOTE

- <samp>What can you say about the figures of repressed and dead in the USSR that were dominant during the Cold War?</samp>

#+BEGIN_QUOTE
It was about discrediting the enemy. Western Sovietologists argued that the number of victims of repression, collectivization, hunger, etc. was around 50-60 millions of people. In 1976, Solzhenitsyn declared that in the period from 1917 to 1959 110 millions were killed. It's hard to comment on this nonsense. In fact, the rate of growth of the population was more than 1%, which exceeded the figures of England or France. In 1926 there were 147 millions of inhabitants in the USSR, 162 millions in 1937, and 170.5 million in 1939. These figures are trustworthy, and they don't agree with murders of tens of millions citizens.
#+END_QUOTE

- <samp>What was the reaction to the numbers you named?</samp>

#+BEGIN_QUOTE
The famous writer Lev Razgon went into polemics with me. He argued that in 1939 there were more than 9 millions of prisoners in the camps, while archives show us another figure: 2 millions. He was moved by emotions and he had access to the television; I, on the other hand, was not welcome there. Later they realized that I was right, and they fell silent.
#+END_QUOTE

- <samp>And what about the West?</samp>

#+BEGIN_QUOTE
In the forefront of my critics there was Robert Conquest, whose figures were 5 times larger than the documentary evidence. In general, the historians have now recognized our numbers. The universities are already teaching my figures.
#+END_QUOTE

- <samp>You got the access to the archives of the Gulag, the NKVD, etc. for the first time thanks to Gorbachev. How accurate are they?</samp>

#+BEGIN_QUOTE
The statistics of the Gulag are considered by our historians to be one of the best.
#+END_QUOTE

- <samp>In other words, the leaders of the country knew exactly the size of their repressions and the number of those shot?</samp>

#+BEGIN_QUOTE
Yes. Stalin was regularly informed. In each case of disappearance or escape of an inmate, they had all his files and all correspondence.
#+END_QUOTE

- <samp>Do you know anything about how Stalin and his entourage argued the need for such violence and murders?</samp>

#+BEGIN_QUOTE
I think they wanted to get rid of people who did not fit into the project of building a communist future. As well as from those who had a strong self-defense instinct, although, technically, they weren't guilty of anything. It was a preventive measure. Molotov told the journalist Felix Chuev a phrase that says a lot: "We did not wait until they betrayed us, we took initiative in our own hands and ahead of them."
#+END_QUOTE

- <samp>What is your opinion, as a historian. To what extent is Russian history unique in terms of high political mortality?</samp>

#+BEGIN_QUOTE
If you compare with the history of England of the 17th century, France of the 18th century and Germany of the 19th century, then the story is unique in that it all happened in the 20th century. When a complex integrated economy was created and buried by the revolution. When in 1920 Herbert Wells came to Russia, he saw the utmost savagery: dismantled railways, there was no electricity, everything was falling apart, and the people were dying from hunger and cold. And prior to that - although Russia was on the European periphery - it was a civil state. We can say that the more a state is civil, the less desirable is the revolution, taking into account the terrible consequences it entails.
#+END_QUOTE

- <samp>You're saying that it is only the proximity to the present era (meaning more modern means of destruction), that makes Stalin more dangerous than Genghis Khan?</samp>

#+BEGIN_QUOTE
Yes.
#+END_QUOTE

- <samp>Does communism and ideology have anything to do with any of this? Does it make sense for a Christian to study the victims of the Catholic Church killed in the name God?</samp>

#+BEGIN_QUOTE
It does make sense, because you can't have an absolute faith in God; this faith is concrete. All those unfortunate people who were burned at the stake, died for the fact that their faith wasn't right, it deviated from the norm and came into conflict with submission to the Pope. Ideology? A new society was being created, and the construction of a communist future required a new man. Those people killed in 1937, did not give in to the change. They've been killing useless people.
#+END_QUOTE

- <samp>Is it reasonable to blame Christ for the Inquisition, or Marx for Stalin?</samp>

#+BEGIN_QUOTE
Marx created his theory for Europe, not Russia, and certainly not for China. No communist regime would make repressions possible; they are possible only when there is a strong and cruel despotic power, for example, in Stalinist Russia or Maoist China. Repression as such was already impossible under Khrushchev, Brezhnev or Deng Xiaoping.
#+END_QUOTE

- <samp>What was crossing your mind when you opened the secret archive of the Gulag for the first time and learned that the number of repressed is much less than what it was believed and told?</samp>

#+BEGIN_QUOTE
At first, it struck me as a surprise. Then I quickly realized that the West was heavily misguided on the matter; but in spite of this, all the conclusions about the terrorist nature of the regime and the repression, remain valid. It's important to remember it to prevent all of this from happening again.
#+END_QUOTE

* Conclusion

As you can see, the real number of the repressed people does not overcome the 4
millions mark. And the number of "corpses" is several times lower. It is still a
huge number, but it's not extreme or extraordinary in any way if you compare it
to the history of revolutions and civil wars in other states. It looks
especially pale if you consider Solzhenitsyn's estimate of 110 millions.

And, frankly, it's very surprising to me that a scientist like yourself could
even think that such a ridiculous figure might be anywhere close to the real
number. Just for a reference, the Second World War has taken the lives of about
27 millions of USSR citizens and after 70 years since its end, every person that
I'm close to, has a family member who died during this war. But I can't say this
about people who were repressed - almost no one from my circles had a relative
in their family who would fall a victim of these repressions. I understand, that
this argument is heavily biased, but still.

To conclude, just as I said in the beginning, I'm not looking to change your
views on the history or the politics, Dr. Peterson. I'm not looking to make you
a Marxist or wear a communist hat. I have the only request for you to stop
giving your audience Solzhenitsyn's false figures and start giving the correct
ones. You may interpret them any way you see fit. Just as Zemskov did, you can
continue to use these numbers to criticize the regime and characterize its deeds
as terror. But I think, the world needs to know the truth. And the truth is that
the consequences of the Communist revolution in Russia were no more bloody than
the consequences of the French revolution that brought liberty, equality and
fraternity to the world. (Soviet Union, in turn, also gave the world a couple of
things, like, the defeat of Hitler's fascism and a first man in space among
other things)

P.S. To support my claim further, I also add 3 links to Zemskov's articles. They
contain pretty much the same outlook, but are much closer to being scientific,
so you may prefer to read those. They are in Russian and unless you know the
language reasonably well, you can use something like google translate (that, I
found, performs reasonably well) and you can ask me for any assistance needed.

1. V. Zemskov. The Gulag (socio-historical aspect). "Social research", #6,#7, 1991. [[https://scepsis.net/library/id_937.html]]
2. V. Zemskov. On the scale of repressions in the USSR. "Social research", #9, 1995 [[https://scepsis.net/library/id_957.html]]
3. V. Zemskov. On the scale of political repressions in the USSR. "Political education", #1 (66), 2012 [[http://www.politpros.com/journal/read/?ID=783][http://www.politpros.com/journal/read/?ID=783]]
